### ISSUE TITLE
[Bug]: IOS App: Embedded subtitles

### ISSUE THREAD

**Issue by Hassan1906** [Stremio/stremio-bugs#1140]
### Stremio Platform

iOS / iPadOS / macOS Native Beta App

### Describe the bug

Stremio IOS app only shows 1 embedded subtitle for videos that provide multiple embedded subtitles. This is a bit problematic when it comes to anime, in which they provide embedded subtitles for other things than dialogue.

### To Reproduce

1. Go to a video which has multiple embedded subtitles 
2. Click on subtitles
3. *You only see one*

### Expected behavior

I expect all the embedded subtitles to be under "subtitle variants".

### Screenshots

![Image](https://github.com/user-attachments/assets/8c6e7564-d180-4a69-827e-cc123a05b129)
![Image](https://github.com/user-attachments/assets/b08592b2-3bf5-4336-af7b-5f739026851f)

Both from same source.

### Smartphone (if applicable)

iPhone XS. IOS 18.3

### Logs

```shell

```

**Comment by abrxu** [comment]
we have almost the same problem but it is in the Samsung TV app, the developers commented that its solved but its not. We have a samsung cu7700 50''

**Comment by AlvinHV** [comment]
@abrxu This bug is caused by VLCKit specifically. I have no idea why it caused as Im just using vlc's api to get it directly. But KSPlayer shows all of the subtitles correctly

**Comment by Hassan1906** [comment]
@AlvinHV Hi. The new player does indeed show all the embedded aubtitles. However, since animes has other type of formatting, it doesn't display it correctly. (VLCkit however does but with only one subtitle)

**Comment by AlvinHV** [comment]
KSPlayer requires us to create our own subtitle view. It wasn't priority right now so for now it just gets text directly and shows in view without considering position and etc.

**Comment by abrxu** [comment]
> [@abrxu](https://github.com/abrxu) This bug is caused by VLCKit specifically. I have no idea why it caused as Im just using vlc's api to get it directly. But KSPlayer shows all of the subtitles correctly
> 
> Samsung TV app uses its own player on the other hand.

do you have the samsung tv app source code available? mayne i can help u with it

**Comment by kKaskak** [comment]
> > [@abrxu](https://github.com/abrxu) This bug is caused by VLCKit specifically. I have no idea why it caused as Im just using vlc's api to get it directly. But KSPlayer shows all of the subtitles correctly
> > 
> > Samsung TV app uses its own player on the other hand.
> 
> do you have the samsung tv app source code available? mayne i can help u with it

Can you explain in detail the issue on Samsung TV Native App?

**Comment by abrxu** [comment]
the issue is simple: we can not use/view embeeded subtitles in the Samsung TV app, but in the desktop app they're there (in the same player, with the same indexed link)

**Comment by AlvinHV** [comment]
@Hassan1906 Should be fixed now.

**Comment by Pashaa25-4** [comment]
![Image](https://github.com/user-attachments/assets/f72ad84d-2425-42c1-932e-93e4f6bff185)
![Image](https://github.com/user-attachments/assets/955353cf-00a2-45d5-9afb-29642a2f4d18)
This issue hasn’t been resolved on my iPad ..it’s still the same ..on the website it has embedded subtitles ..but on Stremio it doesn’t work

**Comment by AlvinHV** [comment]
Could you show me screenshots from web too? Also have you tried opening it with VLCKIT

**Comment by Pashaa25-4** [comment]
![Image](https://github.com/user-attachments/assets/4080d641-9e38-4e33-80ba-5245883f91d9)
![Image](https://github.com/user-attachments/assets/b1ac1fcc-d858-4c39-a805-93592b7d203e)
I’ve tried opening with vlckit and with ksplayer ..same result..only on web it’s working

**Comment by AlvinHV** [comment]
but what you are showing has nothing to do with embedded subtitles. It is subtitle addon that fails. Create new issue for it.

**Comment by Pashaa25-4** [comment]
As you can see on my previous post ..if is on embedded at variants I have no language to select ..on this post ..if is embedded at variants I have English
