### ISSUE TITLE
Stremio Android TV crashing after an unspecified amount of time

### ISSUE THREAD

**Issue by oketariq** [Stremio/stremio-bugs#1464]
### Stremio Platform

Android TV

### Describe the bug

**This is a different issue than #1463 , but it's identical so I've worded it in the same way.**

For the past few months Stremio's mobile Android TV app has been crashing after an unspecified amount of time of playback. Sometimes it's instant, sometimes it's an episode or two.

I've checked the debug logs with logcat and i've found that these are the main errors related to Stremio
```
06-19 13:55:47.215  1799  1799 E .gms.persisten: Not starting debugger since process cannot load the jdwp agent.
06-19 13:55:47.567  3361  3361 I lowmemorykiller: Kill 'com.stremio.one' (913), uid 10093, oom_score_adj 0 to free 1313184kB rss, 144924kB swap; reason: device is low on swap (0kB < 26212kB) and thrashing (313%)
06-19 13:55:47.608  3894  5144 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10053; state: DISABLED
06-19 13:55:47.608  3894  5144 W ActivityManager: Slow operation: 2513ms so far, now at startProcess: done starting proc!
06-19 13:55:47.676  4253  4253 I ThermalService: CPU temperatures: [44.100002, 42.800003]
06-19 13:55:47.786  3894  5150 I ActivityManager: Process com.google.android.tv.remote.service (pid 13031) has died: vis FGS
06-19 13:55:47.790  3894  3928 I libprocessgroup: Successfully killed process cgroup uid 10043 pid 13031 in 0ms
06-19 13:55:47.802  1799  1799 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
```

I've scoured through the issues here and it seems like this bug was also present about a year ago in #722 , but was apparently fixed. I've also seen a lot of people reporting about the same sort of crashes on the r/Stremio subreddit.

The crash always affects the entirety of the system. It basically does a soft reboot of the whole thing. The error also affects both ExoPlayer AND LibVLC, although the logs are from when I was using LibVLC.

I've pasted the full log here starting from when it killed it's first process to clear memory for Stremio: https://pastebin.com/raw/MsQrpK5X
The actual crash happens at 13:55:47.567

### To Reproduce

1. Install any addon that provides content (in my case, i tested this on both Comet and Torrentio. Both with RD)
2. Open any stream from any show (It has a more likely chance of happening the higher the size of the stream)
3. Watch for a while, the crash has a chance of happening at any time.

### Expected behavior

The stream should play without any crashes.

### TV (if applicable)

Device: Chromecast with Google TV (4K)
OS: Android 12, Kernel 4.9.2679
Stremio Version: 1.6.12
Stremio Server: 4.20.8

### Logs

```shell

```

**Comment by CDrosos** [comment]
_"Kill 'com.stremio.one' (913), uid 10093, oom_score_adj 0 to free 1313184kB rss, 144924kB swap; reason: device is low on swap (0kB < 26212kB) and thrashing (313%)"_
Android killed this process cause of low memory, if you can try enabling caching and stop other apps running at the same time and try again
Also stremio beta 5 is way bettor on resources on this situations. Try that too

**Comment by oketariq** [comment]
Yes, it is being killed because its low on memory. But Stremio shouldnt be hogging that much memory. It should unload stuff it doesnt need.

Plus, this is Android TV. Not mobile. There is no beta.

**Comment by CDrosos** [comment]
> Yes, it is being killed because its low on memory. But Stremio shouldnt be hogging that much memory. It should unload stuff it doesnt need.
> 
> Plus, this is Android TV. Not mobile. There is no beta.

Sorry im noob. Stremio for android tv already using stremio-web interface. Didn't know that

**Comment by oketariq** [comment]
> Sorry im noob. Stremio for android tv already using stremio-web interface. Didn't know that

no worries. Stremio android tv does not use the web interface, it uses its own interface and codebase. The android mobile beta is based off of the android tv codebase.

**Comment by TRtomasz** [comment]
clearly your device run low on memory try removing some apps and try again
also at least provide a way for us to try reproduce this like what stream you have tried playing

**Comment by oketariq** [comment]
I basically have nothing installed except YouTube, Stremio and Downloader. Plus the log file already shows it starts killing unnecessary tasks to free up memory before killing Stremio since the memory usage just consistently increases. Stremio should not be exceeding 1GB of memory usage on a 25-minute 1080p stream.
it happens on any stream i believe i specified that. But a stream I remember it happening in is
S2E7 of Shangri-La Frontier, using Torrentio on the stream "[SubsPlease] Shangri-La Frontier - 32 (1080p) [F6E01386]"

As i said though, it's incredibly inconsistent (as in, it can happen 7 times on one stream, the next day itll run smoothly for 2 episodes then start doing it again)

**Comment by girishjk** [comment]
Exact same thing started happening to me in past week or two and Stremio is almost unusable now.
i started setting up an addon on my VPS which I connected my TV using Tailscale. Which, for a couple of days worked fine, and then streams started taking 4+ minutes to load and then crashing (took about 15 seconds before, Stremio runs for about 2 hours every day). My initial through was the VPN is somehow interfering. I removed the add-ons, uninstalled VPN, cleared Stremio data and logged in again. Same results!

Stumbled upon this thread, since initial analysis said memory issues, I force stopped and disabled almost everything I could, including a bunch of system apps, to rule out the possibility that something else got updated and has a memory leak. But no, even after restoring apps and force killing everything else, Stremio still does the same thing.

I did get a few logs and all seem similar to what is pasted above, system starts killing all processes and then kills Stremio.

Now there's about a 10% chance that a stream will start, and even if it starts, it will stutter and crash everything in a few minutes. I always(since before the crashes started) choose the highest quality highest size stream for anything and haven't tried lower size/quality.

I'm not sure how to reproduce this on someone else's device, I've tried a bunch of streams from Torrentio, MediaFusion, Jackett, Orion and Debrid Search, so unlikely it's an addon issue.

**Comment by girishjk** [comment]
Was monitoring top output over adb when this happened and definitely Stremio consuming all the memory before getting killed

```
Was running top -m 5 -o %MEM,CMDLINE -s 1
This is the snip from just before system starts killing everything - 

54.0 com.stremio.one
  7.3 system_server
  6.6 com.google.android.apps.tv.launcherx
  4.4 com.google.android.apps.tv.launcherx:coreservices
  3.7 com.android.vending[H[JTasks: 256 total,   2 running, 254 sleeping,   0 stopped,   0 zombie
  Mem:  2037424K total,  1988588K used,    48836K free,      636K buffers
 Swap:  1018708K total,   342072K used,   676636K free,   293844K cached
400%cpu 138%user   0%nice  81%sys 158%idle   1%iow   9%irq  13%sirq   0%host
[7m[%MEM]CMDLINE                                                                   [0m
[1m 55.2 com.stremio.one[m
  7.3 system_server
  5.6 com.google.android.apps.tv.launcherx
  3.7 com.google.android.inputmethod.latin
  3.6 com.android.vending[H[JTasks: 256 total,   1 running, 255 sleeping,   0 stopped,   0 zombie
  Mem:  2037424K total,  1987832K used,    49592K free,      648K buffers
 Swap:  1018708K total,   373304K used,   645404K free,   280164K cached
400%cpu 134%user   1%nice  90%sys 153%idle   1%iow   8%irq  13%sirq   0%host
[7m[%MEM]CMDLINE                                                                   [0m
 56.6 com.stremio.one
  7.3 system_server
  5.5 com.google.android.apps.tv.launcherx
  3.7 com.google.android.inputmethod.latin
  3.4 com.google.android.apps.tv.launcherx:coreservices
```

Let me know if I can help with gathering any logs or do some experiments.
Thanks


Edit -
This is what it looks like when streams are fine - 

```
[H[JTasks: 257 total,   1 running, 256 sleeping,   0 stopped,   0 zombie
  Mem:  2037424K total,  1923944K used,   113480K free,    15488K buffers
 Swap:  1018708K total,   162092K used,   856616K free,   608912K cached
400%cpu  47%user   4%nice  55%sys 277%idle   0%iow   8%irq   9%sirq   0%host
[7m[%MEM]CMDLINE                                                                   [0m
 27.3 com.stremio.one
 10.8 com.google.android.apps.tv.launcherx
  9.8 system_server
  8.7 com.google.android.gms
  7.3 com.google.android.apps.tv.launcherx:coreservices
```

**Comment by oketariq** [comment]
Thanks for the log @girishjk !

at this point i'm like 99% sure it's a memory leak caused by some Android TV update.

**Comment by girishjk** [comment]
> at this point i'm like 99% sure it's a memory leak caused by some Android TV update.

How did you come to that conclusion?

BTW, since the day after my last comment, I've not seen the issue happening again. I have all auto updates (play store and system) disabled. I haven't downgraded or uninstalled any apps and it suddenly has stabilized since then. Likely a fix was deployed on Stremio backend?

**Comment by oketariq** [comment]
> How did you come to that conclusion?

It has all the characteristics of a memory leak. The memory keeps increasing and it keeps killing processes to compensate until it overflows and kills the application. I don't see what else it could be.

> Likely a fix was deployed on Stremio backend?

For me it has happened far less, but it has still happened. It could very well be an update to the streaming server though.

**Comment by gcampini** [comment]
I'm responding to this thread bc I think my issues are related to @oketariq 's.

My TV is a TCL model, with Android 11. It's 2Go of RAM, small CPU. **Model & Version : V8-R51MT05-LF1V626**

When I'm streaming, the Streamio app and its child processes (external player if any) get killed after an unspecified amount of time. In my case, this goes from 20sec to 5min approximately.

After analysing some logs (see below), I think this might be related to a memory issue, and, as it crashes after some time, potentially and more specifically a memory leak issue.

Also, this bug _seems_ to occur less frequently with lighter sources (1080p, smaller files), but I'm not sure.

Here's the different configurations I've tried (all bugged) :

- Stremio 1.6.12 ARM | ExoPlayer (integrated)
- Stremio 1.6.12 ARM | ExoPlayer (integrated) | Tunneled Playback
- Stremio 1.6.12 ARM | VLC Player (external)
- Stremio 1.5.7 ARM | ExoPlayer (integrated)
- Stremio 1.5.7 ARM | VLC Player (external)

Due to the different configs I've tried and the logs, I don't think this is really a Stremio software specific issue but moreso a bug within the Android/TCL system context and how Stremio uses memory management APIs (malloc, etc.).

I thought about downgrading my Google TV OS to test but I want to make sure this is an issue with my TV/OS before doing so.

```
07-08 09:23:35.111   745  4082 E nvr.BaseNvrHung: send log to diagnosis service, logMD5:EE572592F4351B7CED77589CB32F9B7E, logTag:Crash, logTime:2025-07-08 09:23:35, logDetail:{"pkg":"com.stremio.one","name":"com.stremio.one","c_type":"1","importance":"1","version":"v7048591 (1.5.7)","background":"false","reason":"      #00 pc 00038a54  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (abort+172) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #01 pc 0002e70f  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (scudo::die()+2) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #02 pc 0002e1bb  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (scudo::dieOnMapUnmapError(bool)+30) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #03 pc 0002e797  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (scudo::map(void*, unsigned long, char const*, unsigned long, scudo::MapPlatformData*)+132) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #04 pc 00030df5  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (scudo::MapAllocator<scudo::MapAllocatorCache<32ul, 2097152ul, 0, 1000> >::allocate(unsigned long, unsigned long, unsigned long*, bool)+304) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #05 pc 0002f81f  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::allocate(unsigned long, scudo::Chunk::Origin, unsigned long, bool)+622) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #06 pc 0002fa27  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (scudo_malloc+18) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #07 pc 00029587  \/apex\/com.android.runtime\/lib\/bionic\/libc.so (malloc+18) (BuildId: b27fc28b7bfbdef51ab55284dba5798a)\n      #08 pc 00ad14ec  \/data\/app\/~~32uSaAP0eqZ1n2LPMTfrwA==\/com.stremio.one-nVCQHRGRpIrAtiBgGEzsDw==\/lib\/arm\/libnode.so (node::NodeArrayBufferAllocator::Allocate(unsigned int)+124)\n","repeating":"true","build":"TCL\/G03_4K_GB_NF\/BeyondTV4:11\/RP1A.200622.001\/AR10:user\/release-keys","timestamp":"2025-07-08 09:23:35 +0200","event_id":"FFA8152DE4ABBE62DDFE873B1F7E2604"}
07-08 09:23:35.151   745  4080 E nvr.BaseNvrHung:  getLogLimitValue success rzt = 23
07-08 09:23:38.660   745  1613 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
07-08 09:23:42.042   745  4083 E utils   : packAndCompressLogs Adding = /data/system/nvrhung/crash/com.stremio.one/events.log
07-08 09:23:42.099   745  4083 E utils   : packAndCompressLogs Adding = /data/system/nvrhung/crash/com.stremio.one/kernel.log
07-08 09:23:42.194   745  4083 E utils   : packAndCompressLogs Adding = /data/system/nvrhung/crash/com.stremio.one/version.log
07-08 09:23:42.197   745  4083 E utils   : packAndCompressLogs Adding = /data/system/nvrhung/crash/com.stremio.one/main.log
07-08 09:23:42.387   745  4083 E utils   : packAndCompressLogs Adding = /data/system/nvrhung/crash/com.stremio.one/SYSTEM_TOMBSTONE@1751959414845.txt.gz
07-08 09:23:42.406   745  4083 E utils   : Zip file has been created!
07-08 09:23:42.408   745  4083 E nvr.BaseNvrHung:  getLogLimitValue success rzt = 23
07-08 09:23:42.418   745  4083 E nvr.BaseNvrHung:  setLogLimitValue success nvrhung_crash=22
```

As you can see, the logs from Stremio 1.5.7 show a pretty severe crash related to malloc in the libnode.so lib.

Logs from other versions are not quite the same but all come down to a memory issue, a panic and the kill of processes (including stremio).

**Comment by xkaraman** [comment]
I am also experiencing this with Metz Tv with Android TV. After some time streaming, Android is forced to close background services like Google Play Store and Google Play Services (ANR enabled in developer settings) until eventual forcing the close of the foreground service of Stremio!

Android Version: 11
Kernel Version: 4.9.243+
Stremio Version: 1.6.12

**Comment by Kom4rius** [comment]
I also started experiencing crashes several months ago, tried looking for a solution, but there didn't seem to be any so I stopped using it. The other day I wanted to see if anything changed, but it's still crashing. It doesn't matter if it's a 4K video (plain, DV, or HDR), 1080p, or 720p. Doesn't matter if it's 3h long, an hour, or 30 minutes. I can rarely finish an episode of a short show, let alone watch a movie. It can crash anywhere between 5 seconds and 20 minutes. I've also tried ExoPlayer, VLC, Kodi, MX, and a few other players. They all crash.

**TV specs:**
Model: TCL 55C815
Software Version: V8-R851T02-LF1V727.000041
OS Version: 11
OS Build: PPR1.180610.011
Kernel: 4.14.236+

**Stremio settings:**
Version: 1.6.12
Hardware-accelerated decoding: ON (tried OFF, as well)
Torrent Profile: Ultra-fast
Frame rate matching: disabled (tried all settings)
Tunneled Playback: OFF (tried ON, as well)

All other video apps work fine; I even tried downloading and playing the same files from a stick without any issue.

**Comment by marcoslor** [comment]
For those with this same problem, try turning "Don't keep activities" on, and setting "Background process limit" to "No background processes", on developer settings. 

In my device, if I didn't chose a stream and opened  an external player as soon as a lauched Stremio, it would crash almost immediately. 

After changing that, the app still crashes randomly, but waaaay less often. I can actually watch things now.



I have no idea why stremio is closed source.
Problems like this are extremely annoying, and I think it would be already fixed by the community if it weren't.

**Comment by TRtomasz** [comment]
Memory usage has been improved a lot in last release please try 1.9.12
