### ISSUE TITLE
Linux: Stremio does not prevent screen from turning off while video is playing

### ISSUE THREAD

**Issue by forteller** [Stremio/stremio-bugs#228]
Hi. Thanks for a great product!

My biggest issue with it is one I hope you can fix: When watching videos in any other video player in fullscreen the screen is kept on, no matter what the timer for automatically turning it off or for the PC to go into sleep mode is set to.

This is not the case for Stremio, so the screen starts dimming and I need to move the mouse cursor or press a button multiple times while watching a video to prevent the screen from going blank.

Hope you can look into this. Thank you again!

System: Ubuntu 20.04, Stremio 4.4 beta

**Comment by arunhk3** [comment]
I have the same issue with Stremio not preventing the screen from locking itself while watching a video in fullscreen. It is pretty annoying!

Please let us know with a workaround if the issue is baked into Linux itself.

System: Manjaro 20.0.3, Stremio 4.4.113

**Comment by marinomaria** [comment]
Same issue here!

Ubuntu 20.04, Stremio 4.4.116

**Comment by victorgveloso** [comment]
I think it is fixed. Shouldn't this issue be closed?

**Comment by edizarca** [comment]
Ahh yes it persists! My biggest issue.

**Comment by victorgveloso** [comment]
Actually it should be fixed on the last update. At the time I have commented, the fixing patch wasn't merged and published publicly yet. But now it is and it works on Arch Linux with plasma.

**Comment by TRtomasz** [comment]
Closing as patch has been merged

**Comment by elbc56** [comment]
Seeing this issue has been closed. Sorry but in which version of Stremio are we supposed to see this issue not present ? Using last version of Stremio (4.4.137-1) on Manjaro xfce updated, I'm still able so reproduce the issue.

**Comment by BinaryEnigma01** [comment]
I can confirm, same as @elbc56, that the issue is still present in Manjaro XFCE, tested with stremio version 4.4.142

**Comment by elbc56** [comment]
Please can someone reopen this bug ? The issue is still present in 4.4.159 version (using deb package amd64 in debian 11, mate-desktop). It is really annoying. Thanks.

**Comment by Ventilador** [comment]
for anyone having this issue, im in arch using awesomewm, but im sure any other window manager has to have a similar feature. this will require `xdg-screensaver` which i think comes as part of the [xdg-utils](https://wiki.archlinux.org/title/Xdg-utils), im not sure if its by default on every linux.

what you want to do is run `xdg-screensaver suspend WindowId` ([from the man pages](https://man.archlinux.org/man/xdg-screensaver.1)).
in awesome it can be achieved like this
```lua
client.connect_signal("manage", function(c)
    awful.client.setslave(c)
    c.opacity = 1
    if awesome.startup
        and not c.size_hints.user_position
        and not c.size_hints.program_position then
        -- Prevent clients from being unreachable after screen count changes.
        awful.placement.no_offscreen(c)
    end
    -- the previous code should be already there as its in the default rc.lua
    -- or some variation of it
    if c.name:find("^Stremio -") ~= nil then
        awful.spawn("xdg-screensaver suspend " .. c.window)
    end
end)
```
and also the `resume`
```lua
client.connect_signal("unmanage", function(c)
    if c.name:find("^Stremio -") ~= nil then
        print("Resume")
        awful.spawn("xdg-screensaver resume " .. c.window)
    end
end)
```
good luck!

**Comment by vaknin** [comment]
The issue still exists.

**Comment by victorgveloso** [comment]
> The issue still exists.

What is your system specs (OS, DE, and WM)?

**Comment by vaknin** [comment]
> > The issue still exists.
> 
> What is your system specs (OS, DE, and WM)?
> 
> It works on Gnome and Plasma but it might fail for XFCE and MATE (based on what was discussed in this issue).

OS: Arch
DE: Xfce 4.18
WM: i3

I guess Xfce is the issue.
Do you have a guess about how to solve it?

**Comment by xversion1** [comment]
> > > The issue still exists.
> > 
> > 
> > What is your system specs (OS, DE, and WM)?
> > It works on Gnome and Plasma but it might fail for XFCE and MATE (based on what was discussed in this issue).
> 
> OS: Arch DE: Xfce 4.18 WM: i3
> 
> I guess Xfce is the issue. Do you have a guess about how to solve it?

I guess it's not xfce. I use KDE and have this issue as well, still not solved.

**Comment by vaknin** [comment]
I've found that setting the 'separate window' setting to 'enabled' fixes it, as a workaround.
![image](https://github.com/Stremio/stremio-bugs/assets/26764607/9211ae09-ce3b-4755-a887-6b7a7a03fbfd)

**Comment by xversion1** [comment]
> I've found that setting the 'separate window' setting to 'enabled' fixes it, as a workaround. ![image](https://user-images.githubusercontent.com/26764607/283401444-9211ae09-ce3b-4755-a887-6b7a7a03fbfd.png) You can find it in _Settings -> Player -> Advanced_

This option uses other player to play but then the sub add-on won't work on it.

**Comment by AndreOliveira23** [comment]
Hi everyone! 
I'm using the version 4.4.168 and I had the same issue a couple days ago. I'm currently using Fedora + Sway
I tried to change the default values for each occurrence of 'exec swayidle' that I found, but nothing had really worked.
Finally, after doing a little research, what did the trick for me was adding this custom setting in the final of my config file (placed at `/etc/sway`): `for_window [app_id="stremio"] inhibit_idle fullscreen`.

**Comment by ewanlbc** [comment]
Sorry but the issue still appears for me on Debian 12 with last Stremio version (deb and flatpak). Using only xfce4-power-manager to set off the screen (no sleep, just off) after a while, Stremio does not inhibit nothing. And it is the same if you configure your machine to enter in sleep mode after a while, Stremio is not considered (machine entering in sleep mode even if watching a fullscreen movie). I cannot reopen the issue so I will probably open a new one. Thanks

**Comment by fedebenelli** [comment]
I'm still having this problem in 2025, shouldn't this issue be open?

**Comment by athuld** [comment]
```bash
#!/bin/bash

# Save current settings
ORIG_SAVER_TIMEOUT=$(xset q | grep 'timeout:' | awk '{print $2}')
ORIG_DPMS_STATE=$(xset q | grep 'DPMS is' | awk '{print $3}')

# Disable screen blanking / DPMS
xset s off
xset -dpms
xset s noblank

# Launch Streamio
flatpak run com.stremio.Stremio

# Wait for Streamio to exit, then restore settings
xset s $ORIG_SAVER_TIMEOUT

if [ "$ORIG_DPMS_STATE" = "Enabled" ]; then
  xset +dpms
else
  xset -dpms
fi

```
If you are using X11 you can try out a hacky method like above

**Comment by jastreb** [comment]
this bug is active again in 2026, I would guess app is failing to send inhibit signal and lockscreen/sddm kicks in

**Comment by samtaylorr** [comment]
Can we necro this? As @jastreb has said, the bug is back.

**Comment by Juyuvi** [comment]
Yeah it is back
