### ISSUE TITLE
no info and nothing happened when clicked on play button.

### ISSUE THREAD

**Issue by souvikpodder** [Stremio/stremio-bugs#53]
**nothing is showing on if i clicked on a movie .....**
**No movie info ,no poster....
when i clicked on play button nothing is happening.......**

![2016-04-19](https://cloud.githubusercontent.com/assets/11691954/14647017/703fd950-0679-11e6-838c-6f40458bb647.png)

**Comment by Ivshti** [comment]
This problem may be related to the change to HTTPS in the newest versions, since some firewalls/AVs block https

can you please try: http://dl.strem.io/Stremio%203.5.7.exe


Another possible reason may be corrupt DB. This one is solved by un-installing Stremio, clicking "yes" to the prompt which asks you to remove stremio data. Then install stremio again.

**Comment by HolyThunder** [comment]
Same issue happened to me. "discover" tab loaded the movie list when clicked but the search didn't work and clicking on any movie led to the same screen as @souvikpodder. Reinstalling (while clicking yes to the aforementioned prompt) didn't fix the issue, but the version you linked @Ivshti works.

**Comment by Ivshti** [comment]
@souvikpodder is this still happening? Does the old version fix it?

**Comment by souvikpodder** [comment]
Its fixed automatically...... But don't know the reason which is causing the problem..... New version always works for me... But its the second time when i faved the problem.... But it solved automatically.....don't know the proper reason and what steps to follow to reproduce it or solve it... :(.... But for its working fine.. :)
