### ISSUE TITLE
Can't open installer

### ISSUE THREAD

**Issue by GuilhermeReda** [Stremio/stremio-bugs#56]
Hi,

When i click to open Stremio_Setup.exe a screem appears rapidly and closes.

I'm on windows 10 64bits.
No error appears when I try to open from cmd

**Comment by Ivshti** [comment]
Can you run this command from cmd and then send us logfile.txt

Stremio_Setup.exe /log:logfile.txt

logfile.txt will appear in current working directory

**Comment by GuilhermeReda** [comment]
[logfile.txt](https://github.com/Stremio/stremio-bugs/files/236896/logfile.txt)

**Comment by guivinicius** [comment]
It happened to me this weekend. So I noticed a hang stremio process in scheduled tasks. Just disabled it and everything ran ok.

**Comment by Ivshti** [comment]
We sent this to the software provider of the installer, and they assured us that it's fixed now

Also we haven't received any new reports of this

so I'm assuming it's fixed

**Comment by mgrandoso** [comment]
Same problem here. Can't install the app. i launch the setup and nothing happend. I try the log and is the same that  GuilhermeReda  upload..

**Comment by Ivshti** [comment]
@mgrandoso you can use this installer in the meantime: http://dl.strem.io/Stremio%203.5.13.exe

we'll ping the installer provider to see if the issue has re-surfaced

**Comment by escorpionmax** [comment]
The problem is still present. Even with the latest installer. I can't install it on Windows 10 64 bits. And i don't have any stremio processs in the scheduled tasks

And from what i can see, the issue is old from many years...

Thanks in advance

**Comment by TRtomasz** [comment]
Do you have any error message @escorpionmax ?

**Comment by escorpionmax** [comment]
> Do you have any error message @escorpionmax ?

Hello. No. No error messages. The same it was commented before: that the process is running (which is not the case, and there is not a task created even) and when i click on yes, in the installer, to close the process before install, it starts to install and as soon it starts, it crask without error or anything. I tried to run the setup with the /log option as i saw in another site, and it does not create any log.

I apologize for my english and thanks for the reply

**Comment by TRtomasz** [comment]
and where did you get the latest installer?

**Comment by escorpionmax** [comment]
> and where did you get the latest installer?

https://www.strem.io/download?platform=windows&four=true
