### ISSUE TITLE
LG TV Error decoding

### ISSUE THREAD

**Issue by koukos93** [Stremio/stremio-bugs#892]
Error decoding on almost all files that were working hours ago.

Hi, my tv is LG 55nano866na and had a very good experience almost a year now wirh RD. Today trying to watch any file i get error decoding, after that the tv tries to start the built in media player and again shows: error file not recognised. I was literally watching a show 5 hours ago. I did update the webOs today(04.50.90) but i watched some episodes after the update and it was fine.

When in built in media player it also shows this file does not support sound error
Downloading the same file from RD and playing from usb works fine.

**Comment by nhan92** [comment]
the same issue happened to me today, I have no idea why too, yesterday still ok

**Comment by elerocks** [comment]
Same here. I've experienced different outcomes though:

1. Play video X in stremio, everything loads 
2. Play video X in stremio, crashes stremio and loads internal player that is sometimes able to play the video
3. Play video X in stremio, crashes stremio and loads internal player that is not able to play the video ( "Error: file not recognised"). On second try in Stremio, it works

Mostly on subsequent tries it works in stremio, however, recently it crashed 8 times in row.

**Comment by h-amor1m** [comment]
Same thing happening to me now. It was working flawlessly until last week.
I've tried everything, reinstalled everything, reconfigured everything, I've even factory reseted the LG TV... Nothing works. Did you find any solution?

**Comment by koukos93** [comment]
no never resolved it. i got a android tv box and all is well.

**Comment by TRtomasz** [comment]
New update has been released should be fixed now, thank you for your patience.

**Comment by levynir** [comment]
The same thing happens with version Theater v1.7.1 on WebOS 24. A brand new TV and installation.
The same video plays well in the internal player for a few minutes, then moves to the external player and plays well without subtitles. Then, the next time you try to play the same video, it gives an error message: "The video cannot be played."
Using torrentio plugin to view.

**Comment by ricardovmaiaa** [comment]
Same thing happening now uin 2026, appear "error ocurred when decoding" "open in external player", I was watching a movie for 10minutes ant than that appeared, I do a clean install of Stremio and I can videos again but it happen again! I have a lg55nano tv

**Comment by zei-bit** [comment]
@TRtomasz 

Rooted LG C2 55inch
Software version **23.25.55**

**Issue:**
Playing any media, regardless of size or type results in Error occurred when decoding. 

**Fixes tried:**
- Rebooting TV
- Updating TV from **13.30.80** to the above version.
- Reinstalling Stremio.

Issue still remains.
