### ISSUE TITLE
Black screen during HDR playback on Google TV Streamer

### ISSUE THREAD

**Issue by rexobo** [Stremio/stremio-bugs#941]
**Describe the bug**
When attempting to play HDR video files on the Google TV Streamer device, the screen goes black while the audio continues to play. This issue appears to be affecting several users, as reported in various forums. Standard video files play without any issues.

**To Reproduce**
1. Open Stremio on Google TV Streamer
2. Select any HDR video content.
3. Start playback.
4. The video plays with audio, but the screen remains black.

**Expected behavior**
HDR content should display both video and audio without any issues.

**TV (please complete the following information):**
 - Device: Google TV Streamer (2024)
 - OS: Android TV
 - Version 14

**Additional context**
This issue only affects HDR content. Regular video files play normally with both video and audio working. The same HDR content worked fine on the Chromecast with Google TV (Android 12) using the same TV setup. Basic troubleshooting steps like restarting the device or reinstalling Stremio did not resolve the problem.

**Comment by TRtomasz** [comment]
This is not stremio bug, rather device issue where device cant properly decode some codecs like Dolby vision profile 7 and fallback to hdr10 or hdr10+

**Comment by arodriguezgb** [comment]
I would really love for stremio to convert incompatible codecs with ExoPlayer, there is a video player called Vimu for Google TV that can be used as an external player and it does this and it works. But its not perfect as it cant use external subtitles, and has other issues.

**Comment by RyanEwen** [comment]
+1 to adding support to Stemio/ExoPlayer. I really dislike using Vimu as the player but it's required on Google TV Streamer and FireSticks

**Comment by arodriguezgb** [comment]
Hello Ryan, this issue was fixed on the Google TV Streamer with the last update / security patch from May. ( March maybe ? )

**Comment by RyanEwen** [comment]
Amazing, I'll try going back to ExoPlayer :)

**Comment by harrydbarnes** [comment]
> Amazing, I'll try going back to ExoPlayer :)

I don't think it was fixed, was it?

**Comment by RyanEwen** [comment]
Yes it fixed

**Comment by harrydbarnes** [comment]
> Yes it fixed

Still having the same issue, so not sure it is. For example, played a DV REMUX file, played for a few seconds, then screen went black and then came back stop motion and dimmer. Handshake broken as it doesn't support Profile 7. Doesn't fallback to converting to DV, and breaks playback.
